services:
  db:
    image: postgres:15-alpine
    container_name: dpa_db
    environment:
      POSTGRES_USER: dpa
      POSTGRES_PASSWORD: dpa
      POSTGRES_DB: dpa
    ports: ["5432:5432"]
    volumes:
      - dpa_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dpa -d dpa"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    container_name: dpa_api
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 3001
      DATABASE_URL: postgres://dpa:dpa@db:5432/dpa
      JWT_SECRET: supersecret-local
      FRONTEND_URL: "http://localhost:3000,http://127.0.0.1:3000"
      GENERATE_OPENAPI: "1"
      OTEL_EXPORTER_PROMETHEUS_PORT: "9464"
      STRIPE_SECRET_KEY: "${STRIPE_SECRET_KEY:-}"
      STRIPE_WEBHOOK_SECRET: "${STRIPE_WEBHOOK_SECRET:-}"
    ports:
      - "3001:3001"
      - "9464:9464"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3001/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  web:
    container_name: dpa_web
    build:
      context: ./src
      dockerfile: Dockerfile
    depends_on:
      api:
        condition: service_healthy
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:3001"
      NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: "${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:-pk_test_dummy}"
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus:v2.55.1
    container_name: dpa_prometheus
    command: ["--config.file=/etc/prometheus/prometheus.yml"]
    volumes:
      - ./observability/prometheus/:/etc/prometheus/:ro
    ports: ["9090:9090"]
    depends_on: [api]

  grafana:
    image: grafana/grafana:11.2.0
    container_name: dpa_grafana
    ports: ["3002:3000"]
    volumes:
      - ./observability/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./observability/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./observability/grafana/provisioning/dashboards/dpa-overview.json:/var/lib/grafana/dashboards/dpa-overview.json:ro
    depends_on: [prometheus]

volumes:
  dpa_db_data:
