version: "3.9"
services:
  db:
    image: postgres:16
    container_name: dpa_db
    environment: { POSTGRES_USER: postgres, POSTGRES_PASSWORD: postgres, POSTGRES_DB: postgres }
    ports: [ "5432:5432" ]
    volumes: [ "db_data:/var/lib/postgresql/data" ]
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10
  api:
    build: ./apps/api
    container_name: dpa_api
    env_file: [ ./apps/api/.env ]
    depends_on: { db: { condition: service_healthy } }
    ports: [ "3001:3001" ]
  web:
    build: ./apps/web
    container_name: dpa_web
    environment: [ "NEXT_PUBLIC_API_URL=http://localhost:3001/api" ]
    ports: [ "3000:3000" ]
    depends_on: [ api ]
volumes: { db_data: {} }
