### `devops-pipeline-auditor-std/docker-compose.local.yml`
services:
  db:
    image: postgres:16
    container_name: dpa_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build: ./api
    container_name: dpa_api
    env_file:
      - ./api/.env
    environment:
      - NODE_ENV=development
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3001:3001"

  web:
    build: ./src
    container_name: dpa_web
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:3001
      - NEXT_PUBLIC_API_KEY=dev-demo-apikey   # defina igual ao exibido em GET /auth/me
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  db_data:
