# name: Deploy (Coolify)

# on:
#   workflow_run:
#     workflows: ["Docker Publish (GHCR)"]
#     types: [completed]

# jobs:
#   deploy:
#     if: ${{ github.event.workflow_run.conclusion == 'success' }}
#     runs-on: ubuntu-latest
#     steps:
#       - name: Trigger Coolify Deploy - API
#         run: curl -s -X POST "${{ secrets.COOLIFY_WEBHOOK_API }}" || true
#       - name: Trigger Coolify Deploy - WEB
#         run: curl -s -X POST "${{ secrets.COOLIFY_WEBHOOK_WEB }}" || true
