# name: Docker Publish (GHCR)

# on:
#   push:
#     branches: [ main ]
#     paths:
#       - 'api/**'
#       - 'src/**'

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       packages: write
#     steps:
#       - uses: actions/checkout@v4

#       - name: Log in to GHCR
#         uses: docker/login-action@v3
#         with:
#           registry: ghcr.io
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}

#       - name: Set up Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: Build & Push API
#         uses: docker/build-push-action@v5
#         with:
#           context: ./api
#           push: true
#           tags: ghcr.io/${{ github.repository_owner }}/dpa-api:latest

#       - name: Build & Push WEB
#         uses: docker/build-push-action@v5
#         with:
#           context: ./src
#           push: true
#           tags: ghcr.io/${{ github.repository_owner }}/dpa-web:latest
